export const lightTheme = {
    palette: {
        themePrimary: '#995829',
        themeLighterAlt: '#fbf7f4',
        themeLighter: '#efded3',
        themeLight: '#e0c4af',
        themeTertiary: '#c2906d',
        themeSecondary: '#a5673b',
        themeDarkAlt: '#8a4f25',
        themeDark: '#74431f',
        themeDarker: '#563117',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
    },
};
