export const lightTheme = {
    palette: {
        themePrimary: '#c72259',
        themeLighterAlt: '#fdf4f7',
        themeLighter: '#f6d5e0',
        themeLight: '#eeb3c7',
        themeTertiary: '#dd6f94',
        themeSecondary: '#ce376a',
        themeDarkAlt: '#b31e50',
        themeDark: '#971a44',
        themeDarker: '#6f1332',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
    },
};
